import { state, selectedProfile } from "../../app/state.js";
import { serverCard } from "../../ui/serverCard.js";

export function DashboardView() {
  const profile = selectedProfile();
  const running = state.profiles.filter((p) => p.running).length;
  return `<section>
    <div class="hero"><div><div class="stat-label text-blue-700">Selected profile</div><h2 class="text-5xl font-black text-slate-950 mt-2">${state.selectedProfile || "none"}</h2><p class="text-slate-600 mt-2">${profile ? `${profile.type} · ${profile.workdir}` : "No profile selected"}</p></div><div class="grid gap-2 min-w-44"><button class="btn btn-success" data-action="start" data-profile="${state.selectedProfile}">Start</button><button class="btn btn-warning" data-action="stop" data-profile="${state.selectedProfile}">Stop</button><button class="btn btn-primary" data-go="console">Open console</button></div></div>
    <div class="stat-grid"><div class="stat-card"><span class="stat-label">Core</span><strong class="stat-value">${state.status?.version || "unknown"}</strong><p class="text-sm text-slate-500">MJT Java core</p></div><div class="stat-card"><span class="stat-label">Running</span><strong class="stat-value">${running}</strong><p class="text-sm text-slate-500">active profiles</p></div><div class="stat-card"><span class="stat-label">Profiles</span><strong class="stat-value">${state.profiles.length}</strong><p class="text-sm text-slate-500">configured servers</p></div><div class="stat-card"><span class="stat-label">Mode</span><strong class="stat-value">${state.demo ? "Demo" : "API"}</strong><p class="text-sm text-slate-500">connection mode</p></div></div>
    <div class="layout-2"><div class="card card-pad"><div class="card-head"><h3 class="text-xl font-black">First-run checklist</h3></div><div class="grid gap-3">${check("Login token accepted", true)}${check("At least one profile configured", !!state.profiles.length)}${check("Installer ready", true)}${check("Console selected", !!state.selectedProfile)}</div></div><div class="card card-pad"><div class="card-head"><h3 class="text-xl font-black">Server overview</h3><button class="btn btn-soft btn-sm" data-go="servers">Manage</button></div><div class="server-list">${state.profiles.map((p) => serverCard(p, p.name === state.selectedProfile)).join("") || `<div class="empty">No profiles yet.</div>`}</div></div></div>
  </section>`;
}
function check(text, done) { return `<div class="flex items-center gap-3 rounded-2xl border border-slate-200 p-3 ${done ? "bg-green-50" : "bg-slate-50"}"><span class="h-3 w-3 rounded-full ${done ? "bg-green-500" : "bg-slate-300"}"></span><b>${text}</b></div>`; }
