import { state } from './state.js';
import { api } from '../services/apiClient.js';
import { clearToken } from '../services/storage.js';
import { toast } from '../ui/toast.js';
import { animateIn, pop } from '../ui/animations.js';
import { AuthView } from '../features/auth/AuthView.js';
import { bindAuth } from '../features/auth/AuthController.js';
import { LayoutView } from '../features/layout/LayoutView.js';
import { DashboardView } from '../features/dashboard/DashboardView.js';
import { ServersView } from '../features/servers/ServersView.js';
import { InstallerView } from '../features/installer/InstallerView.js';
import { ConsoleView } from '../features/console/ConsoleView.js';
import { FilesView } from '../features/files/FilesView.js';
import { PlaceholderView } from '../features/placeholder/PlaceholderView.js';
const pageMap={dashboard:DashboardView,servers:ServersView,installer:InstallerView,console:ConsoleView,files:FilesView};
export function createApp(root){async function boot(){renderAuth();if(state.token){try{await api(`/auth/check?token=${encodeURIComponent(state.token)}`);await openPanel();}catch{}}}
function renderAuth(){root.innerHTML=AuthView();bindAuth(openPanel);animateIn('.login-card')}
async function openPanel(){await refreshAll();renderPanel();startLogPolling()}
async function refreshAll(){try{let [status,mc]=await Promise.all([api('/status'),api('/minecraft/status').catch(()=>api('/minecraft/profiles'))]);state.status=status;state.profiles=Array.isArray(mc)?mc:(mc.profiles||[]);state.selectedProfile=state.selectedProfile||status.activeProfile||state.profiles[0]?.name||'';}catch(e){toast(`Refresh failed: ${e.message}`,true)}}
function pageHtml(){return (pageMap[state.page]||PlaceholderView)()}
function renderPanel(){root.innerHTML=LayoutView(pageHtml());bindPanel();animateIn('.card,.hero,.stat')}
function bindPanel(){document.getElementById('logoutBtn').onclick=()=>{clearToken();state.token='';state.demo=false;stopLogPolling();renderAuth()};document.getElementById('refreshBtn').onclick=async()=>{await refreshAll();renderPanel()};document.querySelectorAll('[data-page]').forEach(b=>b.onclick=async()=>{state.page=b.dataset.page;if(state.page==='files')await loadFiles();renderPanel()});document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>{state.page=b.dataset.go;renderPanel()});let sel=document.getElementById('profileSelect');if(sel)sel.onchange=async()=>{state.selectedProfile=sel.value;if(state.page==='files')await loadFiles();renderPanel()};document.querySelectorAll('[data-select-profile]').forEach(c=>c.onclick=e=>{if(e.target.tagName==='BUTTON')return;state.selectedProfile=c.dataset.selectProfile;renderPanel()});document.querySelectorAll('[data-action]').forEach(b=>b.onclick=async()=>{let a=b.dataset.action,p=b.dataset.profile||state.selectedProfile;if(a==='console'){state.selectedProfile=p;state.page='console';renderPanel();return}await action(a,p)});bindInstaller();bindConsole();bindFiles()}
async function action(a,p){if(!p)return toast('Select a profile first',true);try{await api(`/minecraft/${a}`,{method:'POST',body:JSON.stringify({profile:p})});toast(`${a} sent to ${p}`);await refreshAll();renderPanel()}catch(e){toast(`${a} failed: ${e.message}`,true)}}
function bindInstaller(){let btn=document.getElementById('installBtn');if(!btn)return;btn.onclick=installServer;document.querySelectorAll('[data-recipe]').forEach(b=>b.onclick=()=>recipe(b.dataset.recipe))}
function recipe(r){let data={velocity:['velocity','velocity',25565,'512M',false],paper:['paper','smp',25566,'1G',true],purpur:['purpur','lobby',25567,'1G',true]}[r];if(!data)return;document.getElementById('installProvider').value=data[0];document.getElementById('installProfile').value=data[1];document.getElementById('installPort').value=data[2];document.getElementById('installMemory').value=data[3];document.getElementById('installEula').checked=data[4];pop('[data-recipe]')}
async function installServer(){let v=id=>document.getElementById(id).value.trim();let software=v('installProvider').toLowerCase();let payload={software,provider:software,profile:v('installProfile'),version:v('installVersion')||'latest',build:v('installBuild')||'latest',port:Number(v('installPort')||25565),memory:v('installMemory')||'1G',acceptEula:document.getElementById('installEula').checked,force:document.getElementById('installForce').checked};let out=document.getElementById('installOutput');out.textContent=`Installing ${software} profile "${payload.profile}"...`;try{let res=await api('/minecraft/install',{method:'POST',body:JSON.stringify(payload)});out.textContent+=`\nDone.\n${JSON.stringify(res,null,2)}`;state.selectedProfile=payload.profile;await refreshAll();toast(`Installed ${payload.profile}`)}catch(e){out.textContent+=`\nFailed: ${e.message}`;toast(`Install failed: ${e.message}`,true)}}
function bindConsole(){let btn=document.getElementById('sendCommandBtn');if(!btn)return;btn.onclick=sendCommand;document.getElementById('commandInput').addEventListener('keydown',e=>{if(e.key==='Enter')sendCommand()});document.getElementById('pauseLogsBtn').onclick=()=>{state.logsPaused=!state.logsPaused;renderPanel()};document.querySelectorAll('[data-history-command]').forEach(b=>b.onclick=()=>document.getElementById('commandInput').value=b.dataset.historyCommand);loadLogs()}
async function sendCommand(){let input=document.getElementById('commandInput'),cmd=input.value.trim();if(!cmd)return;try{await api('/minecraft/send',{method:'POST',body:JSON.stringify({profile:state.selectedProfile,command:cmd})});state.commandHistory=[cmd,...state.commandHistory.filter(x=>x!==cmd)].slice(0,8);input.value='';await loadLogs();toast('Command sent')}catch(e){toast(`Command failed: ${e.message}`,true)}}
async function loadLogs(){if(state.logsPaused||!state.selectedProfile)return;let out=document.getElementById('consoleOutput');if(!out)return;try{let res=await api(`/minecraft/logs?profile=${encodeURIComponent(state.selectedProfile)}`);out.textContent=(res.lines||[]).join('\n');out.scrollTop=out.scrollHeight}catch(e){out.textContent=`Cannot load logs: ${e.message}`}}
function startLogPolling(){stopLogPolling();state.logsTimer=setInterval(loadLogs,1800)}function stopLogPolling(){if(state.logsTimer)clearInterval(state.logsTimer);state.logsTimer=null}
async function loadFiles(){if(!state.selectedProfile)return;try{let res=await api(`/files/list?profile=${encodeURIComponent(state.selectedProfile)}&path=${encodeURIComponent(state.files.path)}`);state.files.path=res.path||state.files.path;state.files.items=res.items||[]}catch(e){toast(`Load files failed: ${e.message}`,true)}}
function bindFiles(){let r=document.getElementById('fileRefreshBtn');if(!r)return;r.onclick=async()=>{await loadFiles();renderPanel()};document.querySelectorAll('[data-file-open]').forEach(b=>b.onclick=async()=>{let name=b.dataset.fileOpen,type=b.dataset.fileType;if(type==='dir'){state.files.path=(state.files.path==='/'?'':state.files.path)+'/'+name;await loadFiles();renderPanel();return}state.files.selected=(state.files.path==='/'?'':state.files.path)+'/'+name;try{let res=await api(`/files/read?profile=${encodeURIComponent(state.selectedProfile)}&path=${encodeURIComponent(state.files.selected)}`);state.files.content=res.content||'';renderPanel()}catch(e){toast(`Read failed: ${e.message}`,true)}})}
return{boot}}
